### ISSUE TITLE
SdrAngel SoapySDR and BladeRF 

### ISSUE THREAD

**Issue by GkvJeep** [pothosware/SoapyBladeRF#24]
Hi .
https://github.com/f4exb/sdrangel/issues/248

**Comment by guruofquality** [comment]
Not entirely sure why. I guess all of the settings will get called and their defaults applied? Does this work for you? https://github.com/pothosware/SoapyBladeRF/commit/bfb06500baa772b0bbf925ef176da74e652e97fb

**Comment by GkvJeep** [comment]
New problems.
jump_to_bootloader
![next](https://user-images.githubusercontent.com/34664260/48973895-70cd6800-f05b-11e8-863c-7459321a5241.png)

**Comment by guruofquality** [comment]
lol, ok i made that jump to bootloader false too: https://github.com/pothosware/SoapyBladeRF/commit/04f798e6a4c76ab1fb2f3cf19af068f9d473781d

**Comment by GkvJeep** [comment]
This I myself corrected. ;-))
It seems to work.
The question is different.
[error] bladeRF: Invalid erase setting "false" 
p.s
And change Buffer Count, by default 0.

**Comment by guruofquality** [comment]
> And change Buffer Count, by default 0.

0 is automatic

```
    SoapySDR::ArgInfo xfersArg;
    xfersArg.key = "transfers";
    xfersArg.value = "0";
    xfersArg.name = "Num Transfers";
    xfersArg.description = "Number of async USB transfers. Use 0 for automatic";
    xfersArg.units = "bytes";
    xfersArg.type = SoapySDR::ArgInfo::INT;
    xfersArg.range = SoapySDR::Range(0, 32);
    streamArgs.push_back(xfersArg);
```

> Invalid erase setting "false"

Its just an error print, not action is actually taken. I think the errors prints are wrong FWIW and should be changed, but they should not stop you at this point. Hopefully :-)

PS, copy paste terminal output, its just text, no need for a screenshot

**Comment by GkvJeep** [comment]
Hi Josh.
Change resetArg.value to false.

    // Device reset
    SoapySDR::ArgInfo resetArg;
    resetArg.key = "reset";
    resetArg.value = "true";
    resetArg.name = "Reset Device";
    resetArg.description = "Reset the device, causing it to reload its firmware from flash.";

Konstantin.

**Comment by guruofquality** [comment]
Should be fixed now, thank!
