### ISSUE TITLE
Return the status of MINIEXP1  & MINIEXP2 in readStream

### ISSUE THREAD

**Issue by KarlL2** [pothosware/SoapyBladeRF#31]
Hi,

The following commit https://github.com/Nuand/bladeRF/commit/e1d8c61c448d9b8a31f4652c5832a12feb40ee4a introduces the `BLADERF_META_FLAG_RX_HW_MINIEXP1` and `BLADERF_META_FLAG_RX_HW_MINIEXP2` flags (as well as `BLADERF_META_FLAG_RX_HW_UNDERFLOW`). They are added to the status when receiving samples if the corresponding mini expansion IO pin 1 or 2 is asserted.

Those flags are currently not surfaced by the `bladeRF_SoapySDR::readStream` method. I'm not sure how to update the method as it's probably quite specific to the bladeRF 2.0.

**Comment by KarlL2** [comment]
Hi Josh,

for now I modified `bladeRF_SoapySDR::readStream` to add

`flags = md.status & (BLADERF_META_FLAG_RX_HW_UNDERFLOW | BLADERF_META_FLAG_RX_HW_MINIEXP1 | BLADERF_META_FLAG_RX_HW_MINIEXP2);`

as I just want those flags.

It should be possible to create flags in Soapy to make sure those flags don't collide with Soapy flags. 

I could create a pull request, but I'd like to have you opinion on how to do it first.

**Comment by guruofquality** [comment]
If you are worried about flags colliding, I would day that the upper 16 bits are pretty much reserved for "advanced" purposes. But you will have to translate the BLADERF_META_FLAG* into something in the upper bits. I have done exactly this to report metadata/bit fields filled into a packet by an FPGA on another SDR and it worked out great FWIW.

I dont really want to add defines in SoapySDR Constants for very esoteric things like BLADERF_META_FLAG_RX_HW_MINIEXP1 So if it came down to it something like SOAPY_SDR_USER_FLAG0, SOAPY_SDR_USER_FLAG1, etc would have to suffice

* https://github.com/pothosware/SoapySDR/blob/master/include/SoapySDR/Constants.h

Its interesting that there is a underflow associated with the rx as metadata. Are there also valid samples? If it can be treated like an error returning an error code would suffice: https://github.com/pothosware/SoapySDR/blob/master/include/SoapySDR/Errors.h#L68 I might not trust the samples to be good after an underflow on rx (whatever that means).

**Comment by KarlL2** [comment]
Hi Josh,

I added flags `SOAPY_SDR_USER_FLAG0` up to `SOAPY_SDR_USER_FLAG4` in https://github.com/pothosware/SoapySDR/blob/master/include/SoapySDR/Constants.h as you advised (see https://github.com/pothosware/SoapySDR/pull/353).

I then used those 1st 2 flags to surface BLADERF_META_FLAG_RX_HW_MINIEXP1 & 2 (see https://github.com/pothosware/SoapyBladeRF/pull/49).

I didn't surface `BLADERF_META_FLAG_RX_HW_UNDERFLOW` as we don't really know when it happens and what to do with it.
