### ISSUE TITLE
Unable to enable Bias-T with Soapy Sink and/or Source blocks for the BladeRF (2.0 xA4). 

### ISSUE THREAD

**Issue by matt949** [pothosware/SoapyBladeRF#43]
I've tried every possible thing I can find, but I cannot get the Bias-T for the Soapy source or sink blocks in GNURadio for the BladeRF 2.0 xA4 to work. Everything else is fine. I am using GR 3.93 and Soapy 0.7x (latest). 

I don't know if it's just not supported or what the deal is. The Bias-T does work with the gr-osmocom sink/source, etc. I can also turn it on via the bladeRF-cli. 

I've tried all these as arguments, both in quotes and without:

bias=1
biastee=1
biastee=TX
biastee=TX1
biastee=enable
biastee=true

Anyone have any suggesti9ons, or am I going to have to modify source someplace to make it work?

**Comment by guruofquality** [comment]
I dont see it in the source. https://github.com/pothosware/SoapyBladeRF/blob/master/bladeRF_Settings.cpp

People added all kinds of things to the settings API, surprised to see it getting missed
https://github.com/pothosware/SoapyBladeRF/blob/master/bladeRF_Settings.cpp#L928

If you make the change I would love a PR :-)

**Comment by matt949** [comment]
So that's why it doesn't work! I guess I should have looked. I think I'll just put this in as a feature request, but I can modify what I have locally here to do it in the meantime. The reason this is a problem is ever since I went to GR 3.9.x, the gr-osmocom and BladeRF sink blocks both have a 6 second delay on TX. 

I'm using it for video, so the delay is really bad. However, the Soapy one is maybe 1 second.. if that. I'll go over to gr-osmocom and report the delay while I'm at it. 

Thank you for pointing this out to me!
