### ISSUE TITLE
Add new release tag

### ISSUE THREAD

**Issue by Heshyo** [pothosware/SoapyBladeRF#55]
The available [package on Ubuntu is 0.4.1](https://packages.ubuntu.com/jammy/soapysdr-module-bladerf), which dates from Jan 2019.

Could a new tag be added? Also should the maintainers be contacted to update the package?

**Comment by KarlL2** [comment]
Good idea, but please merge https://github.com/pothosware/SoapyBladeRF/pull/56 first.

**Comment by Heshyo** [comment]
@guruofquality Could a new tag be added and a new package released on debian/ubuntu? There's been a few useful modifications since the last package.

**Comment by guruofquality** [comment]
> @guruofquality Could a new tag be added and a new package released on debian/ubuntu? There's been a few useful modifications since the last package.

Good idea. I am updating the changelog: https://github.com/pothosware/SoapyBladeRF/pull/63

**Comment by guruofquality** [comment]
https://github.com/pothosware/SoapyBladeRF/tree/soapy-bladerf-0.4.2

**Comment by KarlL2** [comment]
Thanks Josh. Maybe SoapySDR also needs to have a new release tag, as some new constants were introduced: https://github.com/pothosware/SoapySDR/pull/353 (unless you've handled the case in SoapyBladeRF when they don't exist https://github.com/pothosware/SoapyBladeRF/pull/49#issuecomment-1146608299 ).
